name: interactive_bottom_sheet_example
description: Demonstrates how to use the interactive_bottom_sheet plugin.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  interactive_bottom_sheet:
    # When depending on this package from a real application you should use:
    #   interactive_bottom_sheet: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  flutter_lorem: ^2.0.0
  flutter_map: ^3.1.0
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  cosee_lints: ^0.1.1
  dart_code_metrics: ^5.5.1

flutter:
  uses-material-design: true
