name: interactive_bottom_sheet
description: A new Flutter plugin project.
homepage: https://pub.dev/publishers/cosee.biz/packages
version: 0.0.1


environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  cosee_lints: ^0.0.1
  dart_code_metrics: ^5.4.0


flutter:
  uses-material-design: true

