name: interactive_bottom_sheet
description: A customizable interactive bottom sheet, which lets you interact with the screen behind it.
homepage: https://pub.dev/publishers/cosee.biz/packages
version: 1.0.0
repository: https://github.com/cosee/interactive_bottom_sheet/tree/main
issue_tracker: https://github.com/cosee/interactive_bottom_sheet/issues
screenshots:
  - description: 'Default appearance of InteractiveBottomSheet'
    path: example/screenshots/example.jpeg
topics:
  - bottom-sheet

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  cosee_lints: ^0.2.0
  dart_code_metrics: ^5.7.6

flutter:
  uses-material-design: true
