blank_issues_enabled: false
contact_links:
  - name: Request help
    url: https://github.com/cosee/interactive_bottom_sheet/discussions/categories/request-help
    about: Need assistance or guidance with the interactive_bottom_sheet package? We're here to help!
